# Generated by Django 3.2.9 on 2021-11-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
